//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLchart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLchart()
        {
            this.TBLorders = new HashSet<TBLorder>();
        }
    
        public int TblNum { get; set; }
        public Nullable<int> TblOrderID { get; set; }
        public Nullable<System.TimeSpan> TblReserve { get; set; }
        public string TblStatus { get; set; }
    
        public virtual TBLorder TBLorder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLorder> TBLorders { get; set; }
    }
}
