//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLorderItem
    {
        public int OrderItemID { get; set; }
        public int OrderID { get; set; }
        public int MenuID { get; set; }
        public string Description { get; internal set; }
        public object Price { get; internal set; }
    }
}
