//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLorder
    {
        public int OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
    }
}
